version: "3.9"
services:
  library:
    image: laps78/library:0.1
    volumes:
      - ./:/app
    command: npm run dev
    ports:
      - 80:4747
    envoronnemt:
      - COUNTER_PORT=3002
      - COUNTER_URL=http://localhost
  counter-storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: node:latest
    volumes:
      - ./counter:/app
    working_dir: /app
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    command: npm run dev
    depends_on:
      - library
      - counter-storage
